#!/usr/bin/env python3

"""
loader.py

This module is part of the pycellin package.
It provides functionality to load a GEFF file into a pycellin model.

References:
- geff GitHub: https://github.com/live-image-tracking-tools/geff
- geff Documentation: https://live-image-tracking-tools.github.io/geff/latest/
"""

import importlib.metadata
import warnings
from datetime import datetime
from pathlib import Path
from typing import Any, Literal

import geff
import geff_spec
import networkx as nx

from pycellin.classes import CellLineage, Data, Model, Property, PropsMetadata
from pycellin.custom_types import PropertyType
from pycellin.graph.properties.core import (
    create_cell_coord_property,
    create_cell_id_property,
    create_lineage_id_property,
)
from pycellin.io.utils import (
    _graph_has_node_prop,
    _split_graph_into_lineages,
    _update_edge_prop_key,
    _update_lineage_prop_key,
    _update_lineages_IDs_key,
    _update_node_prop_key,
    check_fusions,
)


def _recursive_dict_search(
    data: dict[str, Any], target_key: str
) -> dict[str, Any] | None:
    """
    Recursively search for a target key in a nested dictionary structure.

    Parameters
    ----------
    data : dict
        The dictionary to search through.
    target_key : str
        The key to search for.

    Returns
    -------
    dict[str, Any] | None
        The dict associated with the target key if found, None otherwise.
    """
    if not isinstance(data, dict):
        return None
    if target_key in data:  # search in the current level
        return data[target_key]
    for value in data.values():  # recursive search in nested dictionaries
        if isinstance(value, dict):
            result = _recursive_dict_search(value, target_key)
            if result is not None:
                return result
    return None


def _identify_lin_id_prop(
    lin_id_prop: str | None,
    geff_track_node_props: dict[Literal["lineage", "tracklet"], str] | None,
    geff_graph: nx.DiGraph,
) -> str | None:
    """
    Identify the lineage ID key from user input or GEFF metadata.

    If lin_id_prop is provided, the function will check that the property exists
    in all nodes of the graph. If not provided, the function will try to infer it
    from the GEFF track_node_props. If that fails, the function will create a new
    'lineage_ID' property.

    Parameters
    ----------
    lin_id_prop : str | None
        Name of the property to identify lineages.
    geff_track_node_props : dict[Literal["lineage", "tracklet"], str] | None
        The track_node_props from GEFF metadata.
    geff_graph : nx.DiGraph
        The GEFF graph.

    Returns
    -------
    str | None
        The identified lineage ID key, or None if not found or inferred.

    Warns
    -----
    UserWarning
        If the provided lin_id_prop is not found in the GEFF graph.
    """
    # TODO: but what if the property is present but not on all nodes?
    error_stack_level = 3

    lin_id_key: str | None = None
    if lin_id_prop is not None:
        if _graph_has_node_prop(geff_graph, lin_id_prop):
            lin_id_key = lin_id_prop
        else:
            warnings.warn(
                f"The provided property '{lin_id_prop}' is not present in the graph. "
                "Lineage identifier will be infered from GEFF metadata.",
                stacklevel=error_stack_level,
            )
            lin_id_prop = None

    if lin_id_prop is None:
        if geff_track_node_props is not None:
            lin_id_key = geff_track_node_props.get("lineage")
        else:
            if _graph_has_node_prop(geff_graph, "lineage_ID"):
                lin_id_key = "lineage_ID"
            else:
                warnings.warn(
                    "No lineage identifier found in GEFF metadata. "
                    "Lineage IDs will be autogenerated.",
                    stacklevel=error_stack_level,
                )
                lin_id_key = None

    return lin_id_key


def _identify_time_prop(
    time_key: str | None,
    geff_md: geff.GeffMetadata | None,
    geff_graph: nx.DiGraph,
) -> str:
    """
    Identify the time property from argument or GEFF metadata.

    If a time key is provided, the function will check that it exists in the graph.
    If not provided or if it doesn't exist, the function will try to infer it
    from the GEFF metadata, first from the display hints, then from the axes.
    In case the function fallbacks to the GEFF axes, it will take time axes in order
    and check if the corresponding key exists in the graph. The first one to be found
    will be returned as the time property.

    Parameters
    ----------
    time_key : str | None
        The key provided to identify time points.
    geff_md : geff.GeffMetadata | None
        The GEFF metadata.
    geff_graph : nx.DiGraph
        The GEFF graph.

    Returns
    -------
    str
        The identified time property.

    Raises
    ------
    ValueError
        If no time property is found or inferred.

    Warns
    -----
    UserWarning
        If the provided time_key is not present in the graph, triggering fallback
        inference from GEFF metadata.
    UserWarning
        If a valid time property is inferred from display hints.
    UserWarning
        If a valid time property is inferred from axes.
    """
    if time_key is not None:
        if not _graph_has_node_prop(geff_graph, time_key):
            warnings.warn(
                f"The provided property '{time_key}' is not present in the graph. "
                "It will be inferred from GEFF metadata, if possible.",
                stacklevel=3,
            )
            time_key = None

    # Fallback to GEFF display hints.
    hints = geff_md.display_hints if geff_md is not None else None
    if time_key is None and hints is not None:
        time_key = getattr(hints, "display_time", None)
        if time_key is not None:
            if _graph_has_node_prop(geff_graph, time_key):
                warnings.warn(
                    f"Valid time property inferred from display hints: '{time_key}'.",
                    stacklevel=3,
                )
            else:
                time_key = None

    # Fallback to GEFF axes.
    axes = geff_md.axes if geff_md is not None else None
    if time_key is None and axes is not None:
        time_axes = [axis for axis in axes if axis.type == "time"]
        for axis in time_axes:
            if axis.name is not None and _graph_has_node_prop(geff_graph, axis.name):
                time_key = axis.name
                warnings.warn(
                    f"Valid time property inferred from axes: '{time_key}'.",
                    stacklevel=3,
                )
                break

    if time_key is None:
        raise ValueError(
            "No valid time property found. Please provide a valid property argument "
            "or ensure that the GEFF file contains a time axis or a time display hint."
        )

    return time_key


def _identify_space_props(
    cell_x_key: str | None,
    cell_y_key: str | None,
    cell_z_key: str | None,
    geff_md: geff.GeffMetadata | None,
    geff_graph: nx.DiGraph,
) -> tuple[str | None, str | None, str | None]:
    """
    Identify the space properties (x, y, z) from arguments or GEFF metadata.

    If space keys are provided, the function will check that they exist in the graph.
    If not provided, the function will try to infer them from the GEFF metadata,
    first from the display hints, then from the axes.

    Parameters
    ----------
    cell_x_key : str | None
        The key provided by the user to identify the x-coordinate.
    cell_y_key : str | None
        The key provided by the user to identify the y-coordinate.
    cell_z_key : str | None
        The key provided by the user to identify the z-coordinate.
    geff_md : geff.GeffMetadata | None
        The metadata from GEFF file.
    geff_graph : nx.DiGraph
        The geff graph.

    Returns
    -------
    tuple[str | None, str | None, str | None]
        The identified space properties.

    Warns
    -----
    UserWarning
        If any of the provided space properties are not found in the graph.
    """
    space_keys = [cell_x_key, cell_y_key, cell_z_key]
    for i, key in enumerate(space_keys):
        if key is not None:
            if not _graph_has_node_prop(geff_graph, key):
                warnings.warn(
                    f"The provided property '{key}' is not present in the graph. "
                    "It will be inferred from GEFF metadata, if possible.",
                    stacklevel=3,
                )
                space_keys[i] = None

    # Fallback to GEFF display hints.
    hints = geff_md.display_hints if geff_md is not None else None
    hint_fields = ["display_horizontal", "display_vertical", "display_depth"]
    for i, (hint_field, key) in enumerate(zip(hint_fields, space_keys)):
        if key is None and hints is not None:
            space_key = getattr(hints, hint_field, None)
            if space_key is not None:
                if _graph_has_node_prop(geff_graph, space_key):
                    warnings.warn(
                        f"Valid space property inferred from display hints: '{space_key}'.",
                        stacklevel=3,
                    )
                else:
                    space_key = None
            space_keys[i] = space_key

    # Fallback to GEFF axes: space axes are consumed in order.
    axes = geff_md.axes if geff_md is not None else None
    if axes is not None:
        space_axes = iter(axis for axis in axes if axis.type == "space")
        for i, key in enumerate(space_keys):
            if key is None:
                for axis in space_axes:
                    if axis.name is not None and _graph_has_node_prop(
                        geff_graph, axis.name
                    ):
                        space_keys[i] = axis.name
                        warnings.warn(
                            f"Valid space property inferred from axes: '{space_keys[i]}'.",
                            stacklevel=3,
                        )
                        break

    return space_keys[0], space_keys[1], space_keys[2]


def _resolve_prop_key(
    new_name: str,
    fallback: str,
    props_dict: dict,
    original_key: str,
    prop_type: str,
) -> str:
    """
    Resolve a unique property key in props_dict by trying new_name and fallback.

    Parameters
    ----------
    new_name : str
        The primary candidate for the new property key.
    fallback : str
        The fallback candidate for the new property key if new_name is already taken.
    props_dict : dict
        The dictionary of existing properties to check for key collisions.
    original_key : str
        The original property key that is being renamed, used for warning messages.
    prop_type : str
        The type of property being renamed (e.g., 'node' or 'edge'),
        used for warning messages.

    Returns
    -------
    str
        A unique property key to use for the new property.

    Warns
    -----
    UserWarning
        If new_name is not already taken in props_dict, a warning is issued
        indicating the rename.
        If new_name is already taken in props_dict, a warning is issued and fallback
        is returned as the new property key.

    Raises
    ------
    KeyError
        If both new_name and fallback are already taken in props_dict, a KeyError
        is raised indicating that the property cannot be registered in the metadata.
    """
    if new_name not in props_dict:
        warnings.warn(
            f"Property '{original_key}' ({prop_type}) has been renamed to '{new_name}'.",
            stacklevel=4,
        )
        return new_name
    if fallback not in props_dict:
        warnings.warn(
            f"Property '{original_key}' ({prop_type}) has been renamed to '{fallback}' "
            f"('{new_name}' was already taken).",
            stacklevel=4,
        )
        return fallback
    raise KeyError(
        f"Cannot register property '{original_key}' ({prop_type}): both "
        f"'{new_name}' and '{fallback}' already exist in properties dictionary."
    )


def _extract_props_metadata(
    md: dict[str, geff_spec.PropMetadata],
    props_dict: dict[str, Property],
    prop_type: PropertyType,
    rename_map: dict[str, dict[str, str]],
) -> None:
    """
    Extract properties metadata from a given dictionary and update the props_dict.

    Parameters
    ----------
    md : dict[str, geff_spec.PropMetadata]
        The dictionary containing properties metadata.
    props_dict : dict[str, Property]
        The dictionary to update with extracted properties metadata.
    prop_type : PropertyType
        The type of property being extracted ('node' or 'edge').
    rename_map : dict[str, dict[str, str]]
        Mutable accumulator mapping property type ('node', 'edge', 'lineage') to
        a dict of ``{old_key: new_key}`` renames. When a key collision forces a
        rename, both the new and the existing property's mappings are recorded here
        so that the graph data can be updated accordingly.

    Raises
    ------
    ValueError
        If an unsupported property type is provided.
    KeyError
        If a property identifier already exists in props_dict for the same property
        type, or if both the primary and fallback rename candidates are already taken
        when resolving a node/edge key collision.
    """
    for key, prop in md.items():
        if key not in props_dict:
            props_dict[key] = Property(
                identifier=key,
                name=prop.name or key,
                description=prop.description or prop.name or key,
                provenance="geff",
                prop_type=prop_type,
                lin_type="CellLineage",
                dtype=prop.dtype,
                unit=prop.unit or None,
            )
        else:
            if props_dict[key].prop_type != prop_type:
                # The key must be unique but it already exists for nodes or edges,
                # so it needs to be renamed.
                if prop_type == "node":
                    current_prefix, other_prefix = "cell", "link"
                elif prop_type == "edge":
                    current_prefix, other_prefix = "link", "cell"
                else:
                    raise ValueError(
                        f"Unsupported property type: {prop_type}. Expected 'node' or "
                        "'edge'."
                    )
                # Resolve a unique name for the new property.
                new_key = _resolve_prop_key(
                    f"{current_prefix}_{key}",
                    f"pycellin_{current_prefix}_{key}",
                    props_dict,
                    key,
                    prop_type,
                )
                props_dict[new_key] = Property(
                    identifier=new_key,
                    name=prop.name or key,
                    description=prop.description or prop.name or key,
                    provenance="geff",
                    prop_type=prop_type,
                    lin_type="CellLineage",
                    dtype=prop.dtype,
                    unit=prop.unit or None,
                )
                rename_map[prop_type][key] = new_key
                # Resolve a unique name for the existing colliding property.
                other_prop_type = props_dict[key].prop_type
                other_key = _resolve_prop_key(
                    f"{other_prefix}_{key}",
                    f"pycellin_{other_prefix}_{key}",
                    props_dict,
                    key,
                    other_prop_type,
                )
                other_prop = props_dict.pop(key)
                other_prop.identifier = other_key
                props_dict[other_key] = other_prop
                rename_map[other_prop_type][key] = other_key
            else:
                # GEFF ensures uniqueness of property keys for nodes and edges
                # separately, so this should never happen.
                raise KeyError(
                    f"Cannot register property '{key}': an identical identifier "
                    f"already exists in properties dictionary for {prop_type}s. "
                    "Please ensure unique property identifiers."
                )


def _extract_lin_props_metadata(
    md: dict[str, Any],
    props_dict: dict[str, Property],
    rename_map: dict[str, dict[str, str]],
) -> None:
    """
    Extract lineage properties metadata from a given dictionary and update the props_dict.

    Parameters
    ----------
    md : dict[str, Any]
        The dictionary containing lineage properties metadata.
    props_dict : dict[str, Property]
        The dictionary to update with extracted lineage properties metadata.
    rename_map : dict[str, dict[str, str]]
        Mutable accumulator mapping property type ('node', 'edge', 'lineage') to
        a dict of ``{old_key: new_key}`` renames. When a key collision forces a
        rename, both the new lineage property's mapping and the existing property's
        mapping are recorded here so that the graph data can be updated accordingly.

    Raises
    ------
    KeyError
        If a property identifier already exists in props_dict for lineages.
    """
    for key, prop in md.items():
        if key not in props_dict:
            props_dict[key] = Property(
                identifier=key,
                name=prop.get("name") or key,
                description=prop.get("description") or prop.get("name") or key,
                provenance="geff",
                prop_type="lineage",
                lin_type="CellLineage",
                dtype=prop.get("dtype"),
                unit=prop.get("unit") or None,
            )
        else:
            if props_dict[key].prop_type != "lineage":
                # Resolve a unique name for the new lineage property.
                new_key = _resolve_prop_key(
                    f"lin_{key}",
                    f"pycellin_lin_{key}",
                    props_dict,
                    key,
                    "lineage",
                )
                props_dict[new_key] = Property(
                    identifier=new_key,
                    name=prop.get("name") or key,
                    description=prop.get("description") or prop.get("name") or key,
                    provenance="geff",
                    prop_type="lineage",
                    lin_type="CellLineage",
                    dtype=prop.get("dtype"),
                    unit=prop.get("unit") or None,
                )
                rename_map["lineage"][key] = new_key
                # Resolve a unique name for the existing colliding property.
                existing_prop_type = props_dict[key].prop_type
                other_prefix = "cell" if existing_prop_type == "node" else "link"
                other_key = _resolve_prop_key(
                    f"{other_prefix}_{key}",
                    f"pycellin_{other_prefix}_{key}",
                    props_dict,
                    key,
                    existing_prop_type,
                )
                other_prop = props_dict.pop(key)
                other_prop.identifier = other_key
                props_dict[other_key] = other_prop
                rename_map[existing_prop_type][key] = other_key
            else:
                raise KeyError(
                    f"Cannot register property '{key}' (lineage): an identical "
                    f"identifier already exists in properties dictionary. "
                    "Please ensure unique property identifiers."
                )


def _build_props_metadata(
    geff_md: geff.GeffMetadata,
    rename_map: dict[str, dict[str, str]],
) -> dict[str, Property]:
    """
    Read and extract properties metadata from geff metadata.

    Parameters
    ----------
    geff_md : geff.GeffMetadata
        The geff metadata object containing properties metadata.
    rename_map : dict[str, dict[str, str]]
        Mutable accumulator mapping property type ('node', 'edge', 'lineage') to
        a dict of ``{old_key: new_key}`` renames. Populated in-place whenever a
        key collision forces a rename during metadata extraction.

    Returns
    -------
    dict[str, Property]
        Dictionary mapping property identifiers to Property objects.
    """
    props_dict: dict[str, Property] = {}
    if geff_md.node_props_metadata:
        _extract_props_metadata(
            geff_md.node_props_metadata, props_dict, "node", rename_map
        )
    if geff_md.edge_props_metadata:
        _extract_props_metadata(
            geff_md.edge_props_metadata, props_dict, "edge", rename_map
        )

    # TODO: for now lineage properties are not associated to a specific tag but stored
    # somewhere in the "extra" field. We need to check recursively if there is a dict
    # key called "lineage_props_metadata" in the "extra" field.
    # For now I keep this, but it should be replaced by geffception at some point.
    if geff_md.extra:
        # Recursive search for the "lineage_props_metadata" key through the "extra"
        # field dict of dicts of dicts...
        lin_props_metadata = _recursive_dict_search(
            geff_md.extra, "lineage_props_metadata"
        )
        if lin_props_metadata is not None:
            _extract_lin_props_metadata(lin_props_metadata, props_dict, rename_map)

    return props_dict


def _get_prop_unit(
    prop: str,
    axis_type: Literal["time", "space"],
    node_props_md: dict[str, geff_spec.PropMetadata] | None,
    axes: list[geff_spec.Axis],
) -> str | None:
    """
    Retrieve the unit for a property from node properties metadata or axes.

    Node properties metadata is checked first. If the unit is missing, the
    function falls back to filtering the axes list by name and type.

    Parameters
    ----------
    prop : str
        The property name to look up.
    axis_type : Literal["time", "space"]
        The axis type to match when searching the axes list.
    node_props_md : dict[str, geff_spec.PropMetadata] | None
        Node properties metadata, keyed by property name.
    axes : list[geff_spec.Axis]
        The list of axes from GEFF metadata.

    Returns
    -------
    str | None
        The unit string if found, otherwise None.

    Raises
    ------
    AssertionError
        If more than one axis matches the given property name and axis type.
    """
    unit = None
    if node_props_md is not None and prop in node_props_md:
        unit = node_props_md[prop].unit
    if unit is None:
        matched_axes = [ax for ax in axes if ax.name == prop and ax.type == axis_type]
        assert len(matched_axes) <= 1, (
            f"Multiple axes with name '{prop}' and type '{axis_type}' found in"
            "GEFF metadata."
        )
        if matched_axes:
            unit = matched_axes[0].unit
    return unit


def _extract_axes_metadata(
    geff_md: geff.GeffMetadata,
    time_prop: str,
    cell_x_prop: str | None,
    cell_y_prop: str | None,
    cell_z_prop: str | None,
) -> dict[str, Any]:
    """
    Extract space and time units from GEFF metadata.

    Units are extracted from node properties metadata if available,
    and from axes metadata if not.

    Parameters
    ----------
    geff_md : geff.GeffMetadata
        The geff metadata object containing axes information.
    time_prop : str
        The time property for the model.
    cell_x_prop : str | None
        The x-coordinate property for the model, if any.
    cell_y_prop : str | None
        The y-coordinate property for the model, if any.
    cell_z_prop : str | None
        The z-coordinate property for the model, if any.

    Returns
    -------
    dict[str, Any]
        Dictionary containing space_unit and time_unit keys.

    Warns
    -----
    UserWarning
        If multiple space units are found in the axes, a warning is issued and no
        space unit is set at the model level.
    UserWarning
        If no unit is found for the time property, a warning is issued and no time
        unit is set at the model level.
    UserWarning
        If no unit is found for any space property, a warning is issued and no space
        unit is set at the model level.
    """
    units_metadata: dict[str, Any] = {}
    node_props_md = geff_md.node_props_metadata
    axes = geff_md.axes or []

    # Time unit.
    time_unit = _get_prop_unit(time_prop, "time", node_props_md, axes)
    if time_unit is None:
        warnings.warn(
            f"No unit found for time property '{time_prop}' in node properties "
            "or axes. Not setting any time unit at the model level.",
            stacklevel=3,
        )
    else:
        units_metadata["time_unit"] = time_unit

    # Space units.
    if cell_x_prop is None and cell_y_prop is None and cell_z_prop is None:
        warnings.warn(
            "No coordinate properties found. "
            "Not setting any space unit at the model level.",
            stacklevel=3,
        )
        return units_metadata

    x_unit = (
        _get_prop_unit(cell_x_prop, "space", node_props_md, axes) if cell_x_prop else None
    )
    y_unit = (
        _get_prop_unit(cell_y_prop, "space", node_props_md, axes) if cell_y_prop else None
    )
    z_unit = (
        _get_prop_unit(cell_z_prop, "space", node_props_md, axes) if cell_z_prop else None
    )

    # Check unicity of space unit.
    space_units = {u for u in [x_unit, y_unit, z_unit] if u is not None}
    if len(space_units) > 1:
        warnings.warn(
            f"Multiple space units found in node properties or axes: {space_units}. "
            "Not setting any space unit at the model level.",
            stacklevel=3,
        )
    elif len(space_units) == 1:
        units_metadata["space_unit"] = space_units.pop()
    else:
        warnings.warn(
            "No unit found for space properties in node properties or axes. "
            "Not setting any space unit at the model level.",
            stacklevel=3,
        )

    return units_metadata


def _extract_generic_metadata(
    geff_file: Path | str, geff_md: geff.GeffMetadata
) -> dict[str, Any]:
    """
    Extract generic metadata for the model based on the GEFF file and its metadata.

    Parameters
    ----------
    geff_file : Path | str
        Path to the GEFF file.
    geff_md : geff.GeffMetadata
        The geff metadata object.

    Returns
    -------
    dict[str, Any]
        Dictionary containing generic metadata.

    Raises
    ------
    importlib.metadata.PackageNotFoundError
        If the pycellin package is not found when trying to get its version.
    """
    metadata: dict[str, Any] = {}
    metadata["name"] = Path(geff_file).stem
    metadata["file_location"] = geff_file
    metadata["provenance"] = "geff"
    metadata["date"] = str(datetime.now())
    try:
        version = importlib.metadata.version("pycellin")
    except importlib.metadata.PackageNotFoundError:
        version = "unknown"
    metadata["pycellin_version"] = version
    metadata["geff_version"] = geff_md.geff_version
    if geff_md.extra is not None:
        metadata["geff_extra"] = geff_md.extra

    return metadata


def _build_generic_metadata(
    geff_file: Path | str,
    geff_md: geff.GeffMetadata,
    time_prop: str,
    cell_x_prop: str | None,
    cell_y_prop: str | None,
    cell_z_prop: str | None,
) -> dict[str, Any]:
    """
    Build and return a dictionary containing pycellin generic metadata.

    Parameters
    ----------
    geff_file : Path | str
        Path to the geff file.
    geff_md : geff.GeffMetadata
        The geff metadata object to read from.
    time_prop : str
        The time property for the model.
    cell_x_prop : str | None
        The x-coordinate property for the model, if any.
    cell_y_prop : str | None
        The y-coordinate property for the model, if any.
    cell_z_prop : str | None
        The z-coordinate property for the model, if any.

    Returns
    -------
    dict[str, Any]
        Dictionary containing generic pycellin metadata.
    """
    metadata = _extract_generic_metadata(geff_file, geff_md)
    units_metadata = _extract_axes_metadata(
        geff_md, time_prop, cell_x_prop, cell_y_prop, cell_z_prop
    )
    metadata.update(units_metadata)
    metadata["reference_time_property"] = time_prop

    return metadata


def _fallback_to_node_keys(geff_graph: nx.DiGraph, reason: str) -> None:
    """
    Fallback to using graph node keys as cell IDs, with a warning.

    Parameters
    ----------
    geff_graph : nx.DiGraph
        The GEFF graph to update with fallback cell IDs.
    reason : str
        The reason for falling back to node keys, included in the warning message.

    Warns
    -----
    UserWarning
        Indicates that the fallback to node keys is occurring and the reason for it.
    """
    warnings.warn(reason, stacklevel=3)
    for node in geff_graph.nodes:
        geff_graph.nodes[node]["cell_ID"] = node


def _ensure_valid_cell_ID(geff_graph: nx.DiGraph, cell_id_key: str | None) -> str:
    """
    Ensure that a valid cell ID property exists and is consistent with graph node IDs.

    If ``cell_id_key`` is None, the function creates a ``cell_ID`` property from
    the NetworkX node keys. If ``cell_id_key`` is provided, it verifies uniqueness of
    the property, that it exists on all nodes and is a positive integer. If not,
    it falls back to creating a ``cell_ID`` property from node keys. If the provided
    property is valid but its values differ from node keys, the graph node keys are
    updated to match the provided IDs to avoid later inconsistencies.

    Parameters
    ----------
    geff_graph : nx.DiGraph
        The GEFF graph to validate or update.
    cell_id_key : str | None
        Name of the node property that identifies cells, or None to derive IDs
        from the graph node keys.

    Returns
    -------
    str
        The name of the property used as cell identifier after validation or fallback.

    Warns
    -----
    UserWarning
        If ``cell_id_key`` is provided but missing on some nodes, triggering a
        fallback to generated ``cell_ID`` values from node keys.
        If ``cell_id_key`` is provided but contains duplicate values across
        nodes, triggering a fallback to generated ``cell_ID`` values from node keys.
    """
    if cell_id_key is None:
        _fallback_to_node_keys(
            geff_graph,
            "No cell identifier property provided. "
            "A 'cell_ID' property will be created from node keys instead.",
        )
        return "cell_ID"

    if not _graph_has_node_prop(geff_graph, cell_id_key):
        _fallback_to_node_keys(
            geff_graph,
            f"The provided property '{cell_id_key}' is not present on all nodes of "
            "the GEFF graph. A 'cell_ID' property will be created from node keys instead.",
        )
        return "cell_ID"

    cell_ids = [geff_graph.nodes[node][cell_id_key] for node in geff_graph.nodes]
    if not all(
        isinstance(cell_id, int) and not isinstance(cell_id, bool) and cell_id >= 0
        for cell_id in cell_ids
    ):
        _fallback_to_node_keys(
            geff_graph,
            f"Values in property '{cell_id_key}' are not all positive integers. "
            "This property cannot be used as cell identifier. "
            "A 'cell_ID' property will be created from node keys instead.",
        )
        return "cell_ID"

    if len(set(cell_ids)) != len(cell_ids):
        _fallback_to_node_keys(
            geff_graph,
            f"Duplicate values found in property '{cell_id_key}' across graph nodes. "
            "This property cannot be used as cell identifier. "
            "A 'cell_ID' property will be created from node keys instead.",
        )
        return "cell_ID"

    mapping = {node: geff_graph.nodes[node][cell_id_key] for node in geff_graph.nodes}
    nx.relabel_nodes(geff_graph, mapping, copy=False)
    return cell_id_key


def _standardize_properties_data(
    lineages: list[CellLineage],
    lin_id_key: str,
    cell_id_key: str,
    cell_x_key: str | None,
    cell_y_key: str | None,
    cell_z_key: str | None,
    rename_map: dict[str, dict[str, str]],
) -> None:
    """
    Standardize properties data in lineages to match pycellin conventions.

    This function updates the property keys in lineage node data to use
    standardized pycellin naming conventions (e.g., 'cell_ID', 'cell_x').
    It also applies any key renames recorded in *rename_map* during metadata
    extraction so that the graph data stays consistent with the metadata.

    Parameters
    ----------
    lineages : list[CellLineage]
        List of CellLineage objects to standardize.
    lin_id_key : str
        The current lineage ID key name. If not "lineage_ID", this property will be
        renamed in two places: (1) as a node attribute on all nodes within each
        lineage, and (2) as a graph attribute for each lineage object.
    cell_id_key : str
        The current cell ID key name.
    cell_x_key : str | None
        The current x-coordinate key name, if any.
    cell_y_key : str | None
        The current y-coordinate key name, if any.
    cell_z_key : str | None
        The current z-coordinate key name, if any.
    rename_map : dict[str, dict[str, str]]
        Accumulator of ``{old_key: new_key}`` renames per property type
        ('node', 'edge', 'lineage') collected during metadata extraction.
        Applied to each lineage's node attributes, edge attributes, and
        graph-level attributes respectively.
    """
    for lin in lineages:
        # Collision renames as recorded during metadata extraction.
        for old_key, new_key in rename_map["node"].items():
            _update_node_prop_key(lin, old_key=old_key, new_key=new_key)
        for old_key, new_key in rename_map["edge"].items():
            _update_edge_prop_key(lin, old_key=old_key, new_key=new_key)
        for old_key, new_key in rename_map["lineage"].items():
            _update_lineage_prop_key(lin, old_key=old_key, new_key=new_key)

        # Standard pycellin property renames.
        if lin_id_key != "lineage_ID":
            _update_node_prop_key(lin, old_key=lin_id_key, new_key="lineage_ID")
        if cell_id_key != "cell_ID":
            _update_node_prop_key(lin, old_key=cell_id_key, new_key="cell_ID")
        if cell_x_key is not None and cell_x_key != "cell_x":
            _update_node_prop_key(lin, old_key=cell_x_key, new_key="cell_x")
        if cell_y_key is not None and cell_y_key != "cell_y":
            _update_node_prop_key(lin, old_key=cell_y_key, new_key="cell_y")
        if cell_z_key is not None and cell_z_key != "cell_z":
            _update_node_prop_key(lin, old_key=cell_z_key, new_key="cell_z")

    if lin_id_key != "lineage_ID":
        _update_lineages_IDs_key(lineages, lin_id_key)


def _standardize_props_metadata(
    props_md: dict[str, Property],
    cell_x_prop: str | None,
    cell_y_prop: str | None,
    cell_z_prop: str | None,
    space_unit: str | None,
    rename_map: dict[str, dict[str, str]],
) -> None:
    """
    Normalize properties metadata to match pycellin conventions.

    This function ensures that standard pycellin properties exist in the metadata
    and renames them to follow pycellin conventions.

    Parameters
    ----------
    props_md : dict[str, Property]
        The properties metadata dictionary to normalize.
    cell_x_prop : str | None
        The current x-coordinate property name, if any.
    cell_y_prop : str | None
        The current y-coordinate property name, if any.
    cell_z_prop : str | None
        The current z-coordinate property name, if any.
    space_unit : str | None
        The space unit to use for coordinate properties.
    rename_map : dict[str, dict[str, str]]
        Accumulator of ``{old_key: new_key}`` renames per property type
        ('node', 'edge', 'lineage') collected during metadata extraction.
        Applied here to ensure that any standard properties that needed to be renamed
        during metadata extraction are also renamed in the metadata dictionary.
    """
    # Ensure standard pycellin properties exist.
    if "cell_ID" not in props_md:
        props_md["cell_ID"] = create_cell_id_property(provenance="geff")
    if "lineage_ID" not in props_md:
        props_md["lineage_ID"] = create_lineage_id_property(provenance="geff")

    # Create or normalize coordinate property keys.
    for axis, geff_key in [
        ("x", cell_x_prop),
        ("y", cell_y_prop),
        ("z", cell_z_prop),
    ]:
        pycellin_key = f"cell_{axis}"
        if geff_key is not None:
            geff_key = rename_map["node"].get(geff_key, geff_key)
            if geff_key in props_md and geff_key != pycellin_key:
                props_md[pycellin_key] = props_md.pop(geff_key)
                props_md[pycellin_key].identifier = pycellin_key
            else:
                props_md[pycellin_key] = create_cell_coord_property(
                    unit=space_unit, axis=axis, provenance="geff"
                )


def load_GEFF(
    geff_file: Path | str,
    lineage_id_prop: str | None = None,
    cell_id_prop: str | None = None,
    cell_x_prop: str | None = None,
    cell_y_prop: str | None = None,
    cell_z_prop: str | None = None,
    time_prop: str | None = None,
    structure_validation: bool = True,
) -> Model:
    """
    Load a GEFF file and return a pycellin model containing the data and metadata.

    Parameters
    ----------
    geff_file : Path | str
        Path to the GEFF file to load.
    lineage_id_prop: str | None, optional
        Name of the property that identifies lineages in the GEFF file.
        If None, the function will try to infer it from the GEFF metadata
        or autogenerate it based on weakly connected components.
    cell_id_prop : str | None, optional
        Name of the property that identifies cells in the GEFF file.
        If None, the default property 'cell_ID' will be created and populated based
        on GEFF IDs array (graph node IDs).
    cell_x_prop : str | None, optional
        Name of the property that identifies the x-coordinate of cells in the GEFF file.
    cell_y_prop : str | None, optional
        Name of the property that identifies the y-coordinate of cells in the GEFF file.
    cell_z_prop : str | None, optional
        Name of the property that identifies the z-coordinate of cells in the GEFF file.
    time_prop : str | None, optional
        Name of the property to use as the reference time property.
        If None, it will be infered from the GEFF metadata.
    structure_validation : bool, optional
        Whether to validate the GEFF file's structure, i.e. to check that it is
        compliant with the GEFF specification. Default is True.

    Returns
    -------
    Model
        A pycellin model containing the data and metadata from the GEFF file.

    Raises
    ------
    ValueError
        If the GEFF graph is undirected, as pycellin does not support undirected graphs.
    """

    # Read the GEFF file.
    geff_graph, geff_md = geff.read(geff_file, structure_validation=structure_validation)
    if not geff_md.directed:
        raise ValueError(
            "The GEFF graph is undirected: pycellin does not support undirected graphs."
        )
    print(geff_md)
    # print(geff_md.node_props_metadata)

    # Identify specific properties.
    lineage_id_prop = _identify_lin_id_prop(
        lineage_id_prop, geff_md.track_node_props, geff_graph
    )
    print(f"LINEAGE ID PROP: {lineage_id_prop}")
    time_prop = _identify_time_prop(time_prop, geff_md, geff_graph)
    cell_x_prop, cell_y_prop, cell_z_prop = _identify_space_props(
        cell_x_prop, cell_y_prop, cell_z_prop, geff_md, geff_graph
    )

    # Extract and dispatch metadata.
    generic_md = _build_generic_metadata(
        geff_file, geff_md, time_prop, cell_x_prop, cell_y_prop, cell_z_prop
    )
    rename_map: dict[str, dict[str, str]] = {"node": {}, "edge": {}, "lineage": {}}
    props_md = _build_props_metadata(geff_md, rename_map)

    # Split the graph into lineages.
    cell_id_prop = _ensure_valid_cell_ID(geff_graph, cell_id_prop)
    lineages = _split_graph_into_lineages(geff_graph, lineage_ID_key=lineage_id_prop)
    if lineage_id_prop is None:
        lineage_id_prop = "lineage_ID"

    # Rename properties to match pycellin conventions.
    _standardize_properties_data(
        lineages,
        lineage_id_prop,
        cell_id_prop,
        cell_x_prop,
        cell_y_prop,
        cell_z_prop,
        rename_map,
    )
    # TODO: reread and tests for _standardize_props_metadata()
    space_unit = generic_md.get("space_unit")
    _standardize_props_metadata(
        props_md, cell_x_prop, cell_y_prop, cell_z_prop, space_unit, rename_map
    )

    # Create the model.
    model = Model(
        model_metadata=generic_md,
        props_metadata=PropsMetadata(props=props_md),
        data=Data({lin.graph["lineage_ID"]: lin for lin in lineages}),
    )
    check_fusions(model)  # pycellin DOES NOT support fusion events

    return model


if __name__ == "__main__":
    geff_file = "/media/lxenard/data/Janelia_Cell_Trackathon/test_pycellin_geff/pycellin_to_geff.geff"
    # geff_file = "B:/Janelia_Cell_Trackathon/anniek_example/exampl_geff.zarr/tracks"
    # geff_file = "/media/lxenard/data/Janelia_Cell_Trackathon/anniek_example/exampl_geff.zarr/tracks"
    # geff_file = "E:/Janelia_Cell_Trackathon/reader_test_graph.geff"
    # geff_file = "/media/lxenard/data/Janelia_Cell_Trackathon/mouse-20250719.zarr/tracks"
    # geff_file = "/media/lxenard/data/Janelia_Cell_Trackathon/test_pycellin_geff/test.zarr"
    # geff_file = (
    #     "/media/lxenard/data/Janelia_Cell_Trackathon/test_pycellin_geff/pycellin_to_geff.geff"
    # )
    # geff_file = "E:/Janelia_Cell_Trackathon/test_pycellin_geff/pycellin_to_geff.geff"
    # geff_file = "/media/lxenard/data/Janelia_Cell_Trackathon/test_trackmate_to_geff/FakeTracks.geff"
    # geff_file = "E:/Janelia_Cell_Trackathon/test_trackmate_to_geff/FakeTracks.geff"

    # Yohsuke's file for geffception
    # geff_file = "/media/lxenard/data/Janelia_Cell_Trackathon/cell_segmentation.zarr/tree.geff"
    # geff_file = "E:/Janelia_Cell_Trackathon/cell_segmentation.zarr/tree.geff"
    # geff_file = "/media/lxenard/data/Janelia_Cell_Trackathon/cell_segmentation.zarr/tree.geff/linage_tree.geff"
    # geff_file = "E:/Janelia_Cell_Trackathon/cell_segmentation.zarr/tree.geff/linage_tree.geff"

    import plotly.io as pio

    # Plotly: set the default renderer to browser so I can visualize plots
    pio.renderers.default = "browser"

    model = load_GEFF(
        geff_file,
        lineage_id_prop="lineage_id",
        time_prop="time",
    )
    print(model)
    print(model.model_metadata)
    # print("props_dict", model.props_metadata.props)
    print("props_dict keys:")
    for k in model.props_metadata.props.keys():
        print(f"\t{k}")
    lineages = model.get_cell_lineages()
    # print(f"Number of lineages: {len(lineages)}")
    # for lin in lineages:
    #     print(lin)
    lin0 = lineages[0]
    # lin7 = model.get_cell_lineage_from_ID(7)
    # lin7.plot(
    #     node_hover_props=[
    #         "cell_ID",
    #         "lineage_ID",
    #         "frame",
    #         "cell_x",
    #         "cell_y",
    #         "track_id",
    #         "seg_id",
    #         "tree_id",
    #     ]
    # )
    # print(lin0.nodes(data=True))
    for node, data in lin0.nodes(data=True):
        print(data.keys())
        break
    # lin0.plot(node_hover_props=["lineage_ID", "seg_id", "time", "track_id", "cell_ID"])

    # cell_id_key
    # lineage_id_key
    # time_key
    # cell_x_key
    # cell_y_key
    # cell_z_key

    # geff_graph, geff_md = geff.read_nx(geff_file, validate=True)
    # print(geff_graph)
    # # Check how many weakly connected components there are.
    # print(
    #     f"Number of weakly connected components: {len(list(nx.weakly_connected_components(geff_graph)))}"
    # )
    # for k, v in geff_graph.graph.items():
    #     print(f"{k}: {v}")
    # # print(graph.graph["axes"][0].unit)

    # if geff_md.directed:
    #     print("The graph is directed.")

    # metadata = {}  # type: dict[str, Any]
    # metadata["name"] = Path(geff_file).stem
    # metadata["file_location"] = geff_file
    # metadata["provenance"] = "geff"
    # metadata["date"] = str(datetime.now())
    # # metadata["space_unit"] =
    # # metadata["time_unit"] =
    # metadata["pycellin_version"] = version("pycellin")
    # metadata["geff_version"] = geff_md.geff_version
    # for md in geff_md:
    #     print(md)
