name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.13"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build

    - name: Pip install pycellin
      run: |
        python -m pip install .[test] -v
        
    - name: Test
      run: |
        pytest

    # - name: Test and coverage generation
    #   run: |
    #     pytest --cov=./ --cov-report=xml

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v5
    #   with:
    #     fail_ci_if_error: true
    #     files: ./coverage/coverage.xml
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     verbose: true